export const SHOW_CURRENT_USER_REQUEST = "SHOW_CURRENT_USER_REQUEST";
export const SHOW_CURRENT_USER_SUCCESS = "SHOW_CURRENT_USER_SUCCESS";

export const AUTH_INFO_SUCCESS = "AUTH_INFO_SUCCESS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const UPDATE_USERNAME_REQUEST = "UPDATE_USERNAME_REQUEST";
export const UPDATE_USERNAME_SUCCESS = "UPDATE_USERNAME_SUCCESS";
export const UPDATE_USERNAME_FAILURE = "UPDATE_USERNAME_FAILURE";


export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_FAILURE";

export const ADD_WATCHLIST_REQUEST = "ADD_WATCHLIST_REQUEST";
export const ADD_WATCHLIST_SUCCESS = "ADD_WATCHLIST_SUCCESS";
export const ADD_WATCHLIST_FAILURE = "ADD_WATCHLIST_FAILURE";

export const REMOVE_WATCHLIST_REQUEST = "REMOVE_WATCHLIST_REQUEST";
export const REMOVE_WATCHLIST_SUCCESS = "REMOVE_WATCHLIST_SUCCESS";
export const REMOVE_WATCHLIST_FAILURE = "REMOVE_WATCHLIST_FAILURE";
